name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Stop & Remove Existing Container
        run: sudo docker rm -f path-cast || true

      - name: Pull Latest Docker Image
        run: sudo docker pull proj/path-cast:latest

      - name: Run Docker Container
        run: sudo docker run -d -p 80:3000 --name path-cast proj/path-cast:latest