name: CD Pipeline

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Stop Existing Container
        run: docker rm -f path-cast || true

      - name: Pull Latest Image
        run: docker pull einhn/path-cast:latest

      - name: Run New Container
        run: docker run -d -p 80:80 --name path-cast einhn/path-cast:latest