name: CD Pipeline

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Stop Existing Container
        run: docker rm -f path-cast || true

      - name: Pull Latest Image
        run: docker pull einhn/path-cast:latest

      - name: Run New Container
        run: docker run -d -p 80:80 --name path-cast einhn/path-cast:latest